name: Deploy

env:
  GITHUB_REPOSITORY_LOWERCASE: ${GITHUB_REPOSITORY,,}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: docker build
        env:
          image_tag: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/server1:${{ github.sha }}
        run: |
          echo image_tag: ${{ env.image_tag }}
          docker build --tag ${{ env.image_tag }} ./src/Server1
          docker push ${{ env.image_tag }}

  deploy:
    # permissions:
    #   contents: none
    runs-on: ubuntu-22.04
    needs: build
    environment: Production
      # name: 'Production'
      # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SOMEAPI_DEPLOYER_CREDENTIALS }}

    - name: TEST
      run: |
        echo pwd: $(pwd)
        echo PWD: $PWD
        ls -lh

    - name: deploy
      uses: azure/arm-deploy@v1
      env:
        biceptemplates: server1ContainerImage=ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/server1:${{ github.sha }}
      with:
        scope: resourcegroup
        # subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./build/main.bicep
        # parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        parameters: ${{ env.biceptemplates }}
        # failOnStdErr: false
        deploymentMode: Complete
