name: Deploy

env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

#permissions:
#  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

#      - name: Log in to GitHub container registry
#        uses: docker/login-action@v1.10.0
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: docker build
        run: |
          docker build --tag ghcr.io/${{ env.REPO }}:${{ github.sha }} ./src/Server1

      - name: docker login
        run: |
          docker login --username ${{ github.actor }} --password ${{ github.token }} ghcr.io

      - name: docker push
        run: |
          docker push ghcr.io/${{ env.REPO }}:${{ github.sha }}

#      - name: Build and push container image to registry
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#          file: ./src/Server1/Dockerfile

#  deploy:
#    permissions:
#      contents: none
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Development'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#    steps:
