name: Deploy

env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

#permissions:
#  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # - name: Lowercase the repo name and username
      #   run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: docker build
        env:
          REPO: ${GITHUB_REPOSITORY,,}
          DOCKER_TAG: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        run: |
          echo REPO: ${{ env.REPO }}
          echo DOCKER_TAG: ${{ env.DOCKER_TAG }}
          docker build --tag ${{ env.DOCKER_TAG }} ./src/Server1
          docker push ${{ env.DOCKER_TAG }}

#  deploy:
#    permissions:
#      contents: none
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Development'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#    steps:
