name: Deploy

env:
  GITHUB_REPOSITORY_LOWERCASE: 'placeholder_GITHUB_REPOSITORY_LOWERCASE'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Repo to lowercase
        run: echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Docker Server1
        env:
          image_tag_server1: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/server1:${{ github.sha }}
        run: |
          echo image_tag: ${{ env.image_tag_server1 }}
          docker build --tag ${{ env.image_tag_server1 }} ./src/Server1
          docker push ${{ env.image_tag_server1 }}

      - name: Docker Server2
        env:
          image_tag_server2: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/server2:${{ github.sha }}
        run: |
          echo image_tag: ${{ env.image_tag_server2 }}
          docker build --tag ${{ env.image_tag_server2 }} ./src/Server2
          docker push ${{ env.image_tag_server2 }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment: Production

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Repo to lowercase
      run: echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SOMEAPI_DEPLOYER_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      env:
        image_tag_server1: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/server1:${{ github.sha }}
        image_tag_server2: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/server2:${{ github.sha }}
      with:
        scope: subscription
        template: ./build/main.bicep
        parameters: 'containerImageRevisionSuffix=${{ github.sha }} server1ContainerImage=${{ env.image_tag_server1 }} server2ContainerImage=${{ env.image_tag_server2 }} environmentRgName=${{ secrets.AZURE_ENVIRONMENT_RG }} apiRgName=${{ secrets.AZURE_API_RG }} processingRgName=${{ secrets.AZURE_PROCESSING_RG }}'
        deploymentMode: Complete
        deploymentName: ${{ github.sha }}
